name: renew-blog-api
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-mirror:
   if: github.repository == '<owner>/<repo>'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
       with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
         repositories: <target-repo>
     - uses: actions/checkout@v4
       with:
         token: ${{ steps.app-token.outputs.token }}
      - run: |
          git remote add mirror https://github.com/<owner>/<target-repo>.git
          git push mirror -f
