name: The-Infinitys_Blog-index
run-name: making repository-index...
on: push
permissions:
  repository-projects: write
jobs:
  repository_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python ./.github/workflows/repository-index.py
